<<<<<<< HEAD
from enum import Enum

PAGE_APP_BAR_TITLE = "Anotador do PharmaSys"
PAGE_TITLE = "PharmaSys"
LOGOUT = "Logout"
ABOUT = "Sobre"
HELP = "Ajuda"
CONFIGS = "Configurações"
CHARTS = "Relatórios"
LOGIN = "Login"
INSERT_NUMBERS = "Insira Valores numéricos!"
NO = "Não"
YES = "Sim"
PLS_CONFIRME = "Por favor,  CONFIRME:"
DELETE_ITEM = "Deseja realmente DELETAR este item?"
FAIL = "Falha ao salvar"
FILL_FIELDS = "Preencha todos os campos!"
NOT_REGISTERED = "Não Cadastrado"
SUCCESS = "Salvo com Sucesso"
WANT_TO_REGISTER = "Deseja Cadastrar este produto?"
PROD_NOTFOUND = "Produto não cadastrado"
COLUMN_5 = "Ações"
COLUMN_4 = "Valor"
COLUMN_3 = "Apresentação"
COLUMN_2 = "Quantidade"
COLUMN_1 = "Produto"
COLUMN_0 = "Data/Hora"
FT_ANOTA = "Anotações"
APP_NAME = "PharmaSys"
SUNDAY = "Domingo"
SATURDAY = "Sábado"
FRIDAY = "Sexta"
THURSDAY = "Quinta"
WEDNESDAY = "Quarta"
TUESDAY = "Terça"
MONDAY = "Segunda"
DELETE = "Apagar"
CONFIRM = "Confirmar"
PRESENTATION = "Apresentação"
VALUE = "Valor"
QUANTITY = "Quantidade"
PRODUCT_NAME = "Nome do Produto"


class Presentations(Enum):
    UNITY = "Unidade"
    CARD = "Cartela"
    BOX = "Caixa"
    BOTTLE = "Frasco"
    ENVELOPE = "Evelope"


SAVE = "Salvar"
NEW_REGISTER = "Novo Cadastro"
PRODUCT_CODE = "Código:"
NAME = "Nome:"
DESCRIPTION = "Descrição:"
MANUFACTURER = "Fabricante:"
TOTAL_IN_STOCK = "Total em Estoque:"
PRICE = "Preço:"
GENERIC_DRUG = "Medicamento Genérico:"
VALID_DATE = "Validade:"
LOTE = "Lote:"
SEARCH_FIELD = "Digite ou Pesquise"
CLOSE_DAY = "Fechar Dia"
=======
from enum import Enum

PAGE_APP_BAR_TITLE = "Anotador do PharmaSys"
PAGE_TITLE = "PharmaSys"
LOGOUT = "Logout"
ABOUT = "Sobre"
HELP = "Ajuda"
CONFIGS = "Configurações"
CHARTS = "Relatórios"
LOGIN = "Login"
INSERT_NUMBERS = "Insira Valores numéricos!"
NO = "Não"
YES = "Sim"
PLS_CONFIRME = "Por favor,  CONFIRME:"
DELETE_ITEM = "Deseja realmente DELETAR este item?"
FAIL = "Falha ao salvar"
FILL_FIELDS = "Preencha todos os campos!"
NOT_REGISTERED = "Não Cadastrado"
SUCCESS = "Salvo com Sucesso"
WANT_TO_REGISTER = "Deseja Cadastrar este produto?"
PROD_NOTFOUND = "Produto não cadastrado"
COLUMN_5 = "Ações"
COLUMN_4 = "Valor"
COLUMN_3 = "Apresentação"
COLUMN_2 = "Quantidade"
COLUMN_1 = "Produto"
COLUMN_0 = "Data/Hora"
FT_ANOTA = "Anotações"
APP_NAME = "PharmaSys"
SUNDAY = "Domingo"
SATURDAY = "Sábado"
FRIDAY = "Sexta"
THURSDAY = "Quinta"
WEDNESDAY = "Quarta"
TUESDAY = "Terça"
MONDAY = "Segunda"
DELETE = "Apagar"
CONFIRM = "Confirmar"
PRESENTATION = "Apresentação"
VALUE = "Valor"
QUANTITY = "Quantidade"
PRODUCT_NAME = "Nome do Produto"


class Presentations(Enum):
    UNITY = "Unidade"
    CARD = "Cartela"
    BOX = "Caixa"
    BOTTLE = "Frasco"
    ENVELOPE = "Evelope"


SAVE = "Salvar"
NEW_REGISTER = "Novo Cadastro"
PRODUCT_CODE = "Código:"
NAME = "Nome:"
DESCRIPTION = "Descrição:"
MANUFACTURER = "Fabricante:"
TOTAL_IN_STOCK = "Total em Estoque:"
PRICE = "Preço:"
GENERIC_DRUG = "Medicamento Genérico:"
VALID_DATE = "Validade:"
LOTE = "Lote:"
SEARCH_FIELD = "Digite ou Pesquise"
CLOSE_DAY = "Fechar Dia"
>>>>>>> c374d74de493e204019611bbf5f80e1d066c2a4e
